{% set name = "litserve" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/litserve-{{ version }}.tar.gz
  sha256: 49b6828122ff5e252260410a9d22bc006079a6a88c7a8a04e2e6c641bb38fc73

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - fastapi >=0.100
    - httpx
    - uvicorn >=0.29.0

test:
  imports:
    - litserve
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/litserve
  summary: Lightweight AI server.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aniketmaurya
    - borda
    - synapticarbors
