{% set name = "litserve" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/litserve-{{ version }}.tar.gz
  sha256: 25d3f624a30159afec0d77ff0f66671a5565e2d0c0383009238f00b084686eb1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - litserve = litserve.__main__:main

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - uvicorn >=0.29.0
    - python >=3.8
    - fastapi >=0.100
    - httpx
    - uvicorn-standard >=0.29.0

test:
  imports:
    - litserve
  commands:
    - litserve -h
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/litserve
  summary: Lightweight AI server.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aniketmaurya
    - borda
    - synapticarbors
