{% set name = "litserve" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/litserve-{{ version }}.tar.gz
  sha256: a427779e9310c94c3c036b8b8075538e299530800ee9e75b2a27b6437ad74c42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - litserve = litserve.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - pyzmq >=22.0.0
    - python >={{ python_min }}
    - fastapi >=0.100
    - uvicorn-standard >=0.29.0

test:
  imports:
    - litserve
  commands:
    - litserve -h
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Lightning-AI/litserve
  summary: Lightweight AI server.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aniketmaurya
    - borda
    - synapticarbors
