schema_version: 1

context:
  name: litserve
  version: 0.2.14

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/litserve-${{ version }}.tar.gz
  sha256: be513b73a4d09b66f5a9608a2479e6d421af0a79e7b61fccb208c522253f990d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - litserve = litserve.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - pyzmq >=22.0.0
    - python >=${{ python_min }}
    - fastapi >=0.100
    - uvicorn-standard >=0.29.0

tests:
  - python:
      imports:
        - litserve
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - litserve -h

about:
  summary: Lightweight AI server.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Lightning-AI/litserve

extra:
  recipe-maintainers:
    - aniketmaurya
    - borda
    - synapticarbors
