schema_version: 1

context:
  name: litserve
  version: 0.2.18

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/litserve-${{ version }}.tar.gz
  sha256: 68730d9c01469edbc62bd00988e4e328cceb98a622b50a2dd777f888a9759d1d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - litserve = litserve.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - pyzmq >=22.0.0
    - python >=${{ python_min }}
    - fastapi >=0.112
    - uvicorn >=0.29.0
tests:
  - python:
      imports:
        - litserve
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - litserve -h

about:
  summary: Lightweight AI server.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Lightning-AI/litserve

extra:
  recipe-maintainers:
    - aniketmaurya
    - borda
    - synapticarbors
